version: '3.8'
 
services:
  base:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./base:/base
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./env/.env.dev
 
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info -P solo
    volumes:
      - ./base:/base
    env_file:
      - ./env/.env.dev
    depends_on:
      - redis
      - base