version: '3.4'
 
services:
  app:
    build: .
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: app
    expose:
      - "8000"
    hostname: app
    image: app-image
    networks:
      - main
    restart: on-failure
 
  redis:
    image: redis:alpine
    
  celery_worker:
    command: celery -A BYOL worker -l info -P solo
    container_name: celery_worker
    depends_on:
      - app
      - redis
    hostname: celery_worker
    image: app-image
    networks:
      - main
    restart: on-failure