# Generated by Django 4.1.1 on 2022-11-18 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'APT Group',
            },
        ),
        migrations.CreateModel(
            name='AttackSubTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New ATT&CK Sub-Technique', max_length=50)),
                ('attackid', models.CharField(default='.000', max_length=4, verbose_name='ATT&CK ID')),
            ],
            options={
                'verbose_name': 'ATT&CK Sub-Technique',
            },
        ),
        migrations.CreateModel(
            name='AttackTactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New ATT&CK Tactic', max_length=20)),
                ('attackid', models.CharField(default='TA0000', max_length=6, verbose_name='ATT&CK ID')),
            ],
            options={
                'verbose_name': 'ATT&CK Tactic',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Objective',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Scan', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('STOPPED', 'STOPPED'), ('COMPLETED', 'COMPLETED'), ('RUNNING', 'RUNNING')], default='STOPPED', max_length=15)),
                ('ip', models.CharField(default='127.0.0.1', max_length=15, verbose_name='IP Address')),
                ('username', models.CharField(default='admin', max_length=30, verbose_name='Machine Username')),
                ('password', models.CharField(default='admin', max_length=50, verbose_name='Machine Password')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Scan',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Binary', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('APT', models.ManyToManyField(blank=True, to='base.apt', verbose_name='APT Groups')),
                ('Objective', models.ManyToManyField(to='base.objective', verbose_name='Objectives')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'LOLBin',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Variant', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=6)),
                ('payload', models.TextField(default=None, verbose_name='Generic Payload')),
                ('defaultPayload', models.TextField(default=None, verbose_name='Default Payload')),
                ('cleanup', models.TextField(blank=True, null=True, verbose_name='Generic Cleanup')),
                ('defaultCleanup', models.TextField(blank=True, null=True, verbose_name='Default Cleanup')),
                ('description', models.TextField(blank=True, null=True)),
                ('detection', models.TextField(blank=True, null=True, verbose_name='Detection Guide')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='Prevention Guide')),
                ('mitre', models.TextField(blank=True, null=True, verbose_name='MITRE ATT&CK')),
                ('lolbas', models.TextField(blank=True, null=True, verbose_name='LOLBAS Project')),
                ('AttackSubTechnique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.attacksubtechnique', verbose_name='ATT&CK Sub-Technique')),
                ('Objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.objective')),
                ('Technique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technique')),
            ],
            options={
                'verbose_name': 'Variant',
            },
        ),
        migrations.CreateModel(
            name='UserVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(default=None)),
                ('cleanup', models.TextField(blank=True, null=True)),
                ('Variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.variant')),
            ],
            options={
                'verbose_name': 'Custom Variant',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Template', max_length=200)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('Scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.scan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Template',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Simulation', max_length=200)),
                ('Scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.scan')),
                ('Template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.template')),
                ('UserVariant', models.ManyToManyField(blank=True, to='base.uservariant')),
                ('Variant', models.ManyToManyField(blank=True, to='base.variant')),
            ],
            options={
                'verbose_name': 'Simulation',
            },
        ),
        migrations.CreateModel(
            name='AttackTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New ATT&CK Technique', max_length=50)),
                ('attackid', models.CharField(default='T0000', max_length=5, verbose_name='ATT&CK ID')),
                ('AttackTactic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.attacktactic', verbose_name='Parent Tactic')),
            ],
            options={
                'verbose_name': 'ATT&CK Technique',
            },
        ),
        migrations.AddField(
            model_name='attacksubtechnique',
            name='AttackTechnique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.attacktechnique', verbose_name='Parent Technique'),
        ),
    ]
