# Generated by Django 4.1.1 on 2022-11-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservariant',
            options={'ordering': ['id'], 'verbose_name': 'Custom Variant'},
        ),
        migrations.AlterField(
            model_name='variant',
            name='Technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technique', verbose_name='Binary Used'),
        ),
    ]
