# Generated by Django 4.1.1 on 2022-11-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_uservariant_options_alter_variant_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='Variant',
        ),
    ]
