# Generated by Django 4.1.1 on 2022-11-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_simulation_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='name',
            field=models.CharField(default='Custom Variant', max_length=200),
        ),
    ]
