# Generated by Django 4.1.1 on 2022-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_uservariant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='detected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
