# Generated by Django 4.1.1 on 2022-11-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_uservariant_detected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariant',
            name='Variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.variant'),
        ),
    ]
