# Generated by Django 4.1.1 on 2022-11-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_uservariant_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='chain',
            field=models.BooleanField(default=False),
        ),
    ]
