# Generated by Django 4.1.1 on 2022-11-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_uservariant_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservariant',
            name='chain',
        ),
        migrations.AddField(
            model_name='uservariant',
            name='chainPrevious',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
