# Generated by Django 4.1.1 on 2022-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_uservariant_chain_uservariant_chainprevious'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariant',
            name='chainPrevious',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Chain To Previous'),
        ),
    ]
