# Generated by Django 4.1.1 on 2022-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_uservariant_chainprevious'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
