# Generated by Django 4.1.1 on 2022-11-28 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_uservariant_highintegrity_glob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glob',
            name='Variant',
        ),
        migrations.AddField(
            model_name='glob',
            name='Technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technique'),
        ),
    ]
