# Generated by Django 4.1.1 on 2022-11-28 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_glob_variant_glob_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='glob',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glob',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
